import Head from 'next/head'
import { useRouter } from "next/router"
import NavBar from './NavBar';

import { CommonContainer, Footer } from './../styles/styleModules'

export default function Layout({children}) {
    const { pathname } = useRouter()
    return(
        <div className="layout">
            <Head >
                <title>Highlights and Blackouts - Heather Bowlan</title> 
                <meta name = "description"content = "Generated by create next app" />
                <link rel = "icon" href = "/favicon.ico" />
            </Head>
            {
                (pathname !== "/") && <NavBar/>
            }
            
            <CommonContainer>
                <main className="container">{children}</main>
            </CommonContainer>
            
            <Footer>
                <div className="container">
                    <div id="footerTitle">Highlights&Blackouts</div>
                    <div class="publisher">_mix_lit 2023</div>
                </div>
            </Footer>
        </div>
    );
}

