import Head from 'next/head'
import styles from '../styles/Home.module.css'

import PoemContainer from '../components/PoemContainer'
import BackgroundCarousal from '../components/BackgroundCarousal'
import ErasureControls from '../components/ErasureControls'
import NavBar from '../components/NavBar'

export default function Home() {
  const uiProps = {
    tags:{
      title:"Tags",
      name:"tagCollapse",
      items:[
        {name:"Hopeful"},
        {name:"Sad"},
        {name:"Spaceships"},
      ]
    },
    erasures:{
      title:"Table of Erasings",
      name:"erasureCollapse",
      items:[
        {name:"Erasure 1"},
        {name:"Erasure 2"},
        {name:"Erasure 3"},
      ]
    }
  }

  return ( <div className = { styles.container } >
      <Head >
        <title> Self-Erasings - Heather Bowlan</title> 
        <meta name = "description"content = "Generated by create next app" />
        <link rel = "icon" href = "/favicon.ico" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css" integrity="sha512-wR4oNhLBHf7smjy0K4oqzdWumd+r5/+6QO/vDda76MW5iug4PT7v86FoEkySIJft3XA0Ae6axhIvHrqwm793Nw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css" integrity="sha512-6lLUdeQ5uheMFbWm3CP271l14RsX1xtx+J5x2yeIDkkiBpeVTNhTqijME7GgRKKi6hCqovwCoBTlRBEC20M8Mg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
      </Head>

      <main className = { styles.main } >
        <NavBar />
      
        <div id="erasurePage" className={styles.container}>
          <ErasureControls tags={uiProps.tags} erasures={uiProps.erasures}/>
          <PoemContainer/>
          <BackgroundCarousal/>
        </div>
      </main>

      <footer className = { styles.footer } >
      
      </footer> 
      </div>
  )
}